#!/bin/bash

# Función para mostrar el menú
mostrar_menu() {
    echo "Seleccione una opción: "
    echo "1. Instalar Docker y Docker-compose"
    echo "2. Portainer"
    echo "3. Trasmission"
    echo "4. File Browser"
    echo "5. Jellyfin"
    echo "0. Salir"
}

# Función para leer la opción seleccionada
leer_opcion() {
    local opcion
    read -p "Ingrese su opción: " opcion
    echo $opcion
}

# Bucle principal
opcion=0
while [[ $opcion -ne 4 ]]; do
    mostrar_menu
    opcion=$(leer_opcion)

    case $opcion in
        1)
            # Instalar Docker
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

            # Instalar Docker Compose
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
            # Agregar Carpeta Docker
            sudo mkdir -p $HOME/.docker
            # Agregar usuario al grupo docker
            sudo usermod -aG docker $USER

            clear
            echo "Eco-sistema Docker instalado..."
            echo
            echo
            ;;
        2)
            echo "progreso instalacion completa"
            echo
            echo
            ;;
        3)
            echo "Ha seleccionado la opción 3"
            # Código para la opción 3
            ;;
        
        
        
        
        
        
        
        
        
        
        
        4)
            echo "Ha seleccionado la opción 3"
            # Código para la opción 3
            ;;
        0)
            echo "¡Hasta luego!"
            ;;
        *)
            echo "Opción inválida"
            ;;
    esac
done
