#!/bin/bash

# Función para mostrar el menú
mostrar_menu() {
    echo "Seleccione una opción: "
    echo "1. Instalar Docker y Docker-compose"
    echo "2. Portainer"
    echo "3. Trasmission"
    echo "4. File Browser"
    echo "5. Jellyfin"
    echo "0. Salir"
}

# Función para leer la opción seleccionada
leer_opcion() {
    local opcion
    read -p "Ingrese su opción: " opcion
    echo $opcion
}

# Bucle principal
opcion=0
while [[ $opcion -ne 4 ]]; do
    mostrar_menu
    opcion=$(leer_opcion)

    case $opcion in
        1)
            # Instalar Docker
            #Instalación de Docker:
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            sudo usermod -aG docker $USER
            #Instalación de Docker Compose:
            apt install docker-compose
            #Instalación de Portainer:
            docker volume create portainer_data
            docker run -d -p 8000:8000 -p 9443:9443 --name portainer \
                --restart=always \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v portainer_data:/data \
                portainer/portainer-ce:latest

            clear
            echo "Eco-sistema Docker instalado..."
            echo
            echo
            ;;
        2)
            echo "progreso instalacion completa"
            echo
            echo
            ;;
        3)
            echo "Ha seleccionado la opción 3"
            # Código para la opción 3
            ;;
        
        
        
        
        
        
        
        
        
        
        
        4)
            echo "Ha seleccionado la opción 3"
            # Código para la opción 3
            ;;
        0)
            echo "¡Hasta luego!"
            ;;
        *)
            echo "Opción inválida"
            ;;
    esac
done
