version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "8096:8096"
    volumes:
      - /home/walli/.docker/jellyfin/config:/config
      - /home/walli/multimedia:/media
      