version: '3'
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /home/walli/.docker/trasmission/temp:/mnt/transmission/temp
      - /home/walli/.docker/trasmission/config:/config
      - /home/walli/descargas:/downloads
    ports:
      - 9091:9091      
      - 51413:51413
    network_mode: bridge